### ISSUE TITLE
How to install recordio?

### ISSUE THREAD

**Issue by JarvisUSTC** [plageon/HtmlRAG#10]
When I try the command "python dataset.py" to check the training data, it raised an error.
`ModuleNotFoundError: No module named 'recordio'`
But I can not find any resource to install the correct recordio package. Could you please give me some instructions about installing this package? Look forward to your reply.

**Comment by plageon** [comment]
Thanks! We missed a dependent file. Fixed in [commit](https://github.com/plageon/HtmlRAG/commit/808228f870454fbf8addccd6470d68836d563624).
