### ISSUE TITLE
使用user guide的方法得不到正确的结果

### ISSUE THREAD

**Issue by jesenzhang** [plageon/HtmlRAG#11]
按照userguide的方法，示例的网页可以得到与例子一样的结果，但是换成实际的网页，就只能得到标题和一些无关的元素，比如这个网页https://english.cctv.com/2024/12/06/ARTItHTPzmKsn0LO30wXsQw0241206.shtml?spm=C69523.PwOasl7Qr6J6.MHZUB6bez4SG.21
question= 'What are the three Chinese cultural elements included in the list of intangible cultural heritage?'
embed_model=bge-large-en
embed_html_pruner的结果就不对了：
```
<div>
<div0>
<span0>HOME</span0>
<span1>NEWS</span1>
<span2>PANVIEW</span2>
<span3>SPECIAL REPORTS</span3>
<div>
<span>VIDEO</span>
<ul>
<a0>GLOBAL VIEW</a0>
<a
```

GenHTMLPruner使用的是HTML-Pruner-Phi-3.8B，对embed_html_pruner的结果处理结果：
```
<div0>
<span0>HOME</span0>
<span1>NEWS</span1>
<span2>PANVIEW</span2>
<span3>SPECIAL
```

**Comment by plageon** [comment]
The example HTML document is rather a short one. Real-world HTML documents can be much longer and more complex. To handle such cases, we can configure the following parameters:
```python
# Maximum number of words in a node when constructing the block tree for pruning with the embedding model
MAX_NODE_WORDS_EMBED = 10 
# MAX_NODE_WORDS_EMBED = 256 # a recommended setting for real-world HTML documents
# Maximum number of tokens in the output HTML document pruned with the embedding model
MAX_CONTEXT_WINDOW_EMBED = 60
# MAX_CONTEXT_WINDOW_EMBED = 6144 # a recommended setting for real-world HTML documents
# Maximum number of words in a node when constructing the block tree for pruning with the generative model
MAX_NODE_WORDS_GEN = 5
# MAX_NODE_WORDS_GEN = 128 # a recommended setting for real-world HTML documents
# Maximum number of tokens in the output HTML document pruned with the generative model
MAX_CONTEXT_WINDOW_GEN = 32
# MAX_CONTEXT_WINDOW_GEN = 4096 # a recommended setting for real-world HTML documents
```
Updated the example code for our tookit: https://github.com/plageon/HtmlRAG/commit/644f39a0ed479ddd151bd8d092e9d3dcea880896. We provide a set of recommended parameters for real-word documents.
看起来你用了实例代码的参数配置，处理真实场景的html文档可以试着调整以上几个参数。
