### ISSUE TITLE
assert tag.name == path[-1], f"tag name: {tag.name}, path[-1]: {path[-1]}"

### ISSUE THREAD

**Issue by jesenzhang** [plageon/HtmlRAG#12]
这个新闻网址 https://news.cctv.com/2024/12/12/ARTI90HKRZyxYHBu6Ud5N8Um241212.shtml?spm=C94212.P4YnMod9m2uD.ENPMkWvfnaiV.13

clean_html之后，还是有内容的，经过 build_block_tree(cleaned_html, max_node_words=256)之后
simplified_html = ‘\n\n’

执行到 pruned_html = embed_html_pruner.prune_HTML(simplified_html, block_tree, block_rankings, chat_tokenizer, MAX_CONTEXT_WINDOW_EMBED)

报错如下：

File "/mnt/sdc1/sd/uni_agent/html_rag.py", line 59, in get_html_rag
    pruned_html = embed_html_pruner.prune_HTML(simplified_html, block_tree, block_rankings, chat_tokenizer, MAX_CONTEXT_WINDOW_EMBED)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sd/miniconda3/envs/agent/lib/python3.11/site-packages/htmlrag/pruner.py", line 41, in prune_HTML
    assert tag.name == path[-1], f"tag name: {tag.name}, path[-1]: {path[-1]}"
           ^^^^^^^^^^^^^^^^^^^^
AssertionError: tag name: [document], path[-1]: html

**Comment by jesenzhang** [comment]
将MAX_NODE_WORDS_EMBED设置为256之后block_tree经常是只有一个块了，这样后面似乎没有什么剪枝操作了，是这样的吗？

**Comment by plageon** [comment]
你看自己的html网页长度多试试参数做调整吧

**Comment by jesenzhang** [comment]
这个bug呢？不能自动调整参数的话，这个工具也没法用啊

**Comment by plageon** [comment]
I have tried the html page you provided, with `MAX_NODE_WORDS_EMBED=64`,`MAX_CONTEXT_WINDOW_EMBED=512` , and `BM25HTMLPruner`. Here is the output:
```html
<title>数据说话：对经济政策的预期，怎么看？</title>
<div>
<div0>
<h1>
				数据说话：对经济政策的预期，怎么看？
			</h1>
<div>
<span>玉渊谭天</span>
<span>2024年12月12日 16:26</span>
</div>
</div0>
<span>正在加载</span>
<div1>
<p0>　　今年，全球贸易保护主义逆潮不断，一些国家和地区的局势变化出乎人们的预料。</p0><p1>　　放眼全球，在今年这样的国际局势下，我们沉着应变、综合施策，实现了经济运行总体平稳、稳中有进，这样的成果来之不易。</p1><p2>　　回头看自己，今年，中国经济运行出现一些新的情况和问题，政策出台的频率与力度都很大。</p2><p3>　　<span>但对于不少人来说，即便“考题”再难，大家还是会对“好学生”抱有很高的期待。</span></p3><p4>　　这种期待，在今年，转化成为了对政策的关注——谭主利用大数据手段对2024年中国经济相关讨论进行分析后发现，“政策”是2024年舆论场最为关心的话题。</p4><p5>　　这些政策，瞄准的是中国经济当前面临的外部冲击、有效需求不足、投资增长存在制约等问题。</p5><p6>　　当政策出台后，政策能否有效，是大家最为关心的问题。</p6><p7>　　这些问题，怎么看？</p7><p8>　　今年年初，中国经济开局，就面临着很大的外部挑战。</p8><p9>　　美西方国家不光在国际舆论场炒作“中国经济见顶论”，还实质性地升级贸易保护主义的措施。</p9><p10>　　国际舆论的抹黑，加上美欧所谓的各种“调查”和关税，目标，对准的就是中国正在酝酿培育的新
```

The two parameters above is adjustable according to the length of your HTML document. We currently do not have a automatic adjusting strategy.

**Comment by plageon** [comment]
Add support for Chinese in the latest version [v0.0.5](https://github.com/plageon/HtmlRAG/releases/tag/v0.0.5).
Note that the modeling for Generative HTML Pruner has been modified, [modeling_llama.py](https://github.com/plageon/HtmlRAG/blob/main/llm_modeling/Llama32/modeling_llama.py), and [modeling_phi3.py](https://github.com/plageon/HtmlRAG/blob/main/llm_modeling/Phi35/modeling_phi3.py).
