### ISSUE TITLE
I would like to know where the ./scripts/rerank.sh file is

### ISSUE THREAD

**Issue by Morning-Z** [plageon/HtmlRAG#13]
I would like to know where the ./scripts/rerank.sh file is

**Comment by plageon** [comment]
Where does rerank.sh get involved in this project? Please point out.

**Comment by Morning-Z** [comment]
![1734420238377](https://github.com/user-attachments/assets/568ffb86-57d5-4032-8aa8-ca55a9855781)

**Comment by plageon** [comment]
Thanks! This is a mistake. `rerank.sh` is supposed to be `chunk_rerank.sh`.
Updated in [commit](https://github.com/plageon/HtmlRAG/commit/770ab88929955491f0cc993cce8796374244b94d).
