### ISSUE TITLE
I was wondering which BM25 model you are using

### ISSUE THREAD

**Issue by Morning-Z** [plageon/HtmlRAG#14]
I was wondering which BM25 model you are using.

**Comment by plageon** [comment]
We use bm25 implementation in Langchain, `from langchain_community.retrievers import BM25Retriever`.
Refer to implementation in [chunk_rerank.py](html4rag/chunk_rerank.py) or our toolkit:
```python
from htmlrag import BM25HTMLPruner
bm25_html_pruner = BM25HTMLPruner()
block_rankings=bm25_html_pruner.calculate_block_rankings(question, simplified_html, block_tree)
print(block_rankings)
```

**Comment by plageon** [comment]
Btw, we edited the latest [issue](https://github.com/plageon/HtmlRAG/issues/13#issuecomment-2547759170).

**Comment by Morning-Z** [comment]
Thank you for your response！
