### ISSUE TITLE
can't calculate block rankings with Generative model

### ISSUE THREAD

**Issue by oreo34567** [plageon/HtmlRAG#16]
error when I run the code in https://huggingface.co/zstanjj/HTML-Pruner-Phi-3.8B
ps. I am  using the given short html

ckpt_path = "../llms/HTML-Pruner-Phi-3.8B"
if torch.cuda.is_available():
    device="cuda"
else:
    device="cpu"
gen_embed_pruner = GenHTMLPruner(gen_model=ckpt_path, max_node_words=MAX_NODE_WORDS_GEN, device=device)
block_rankings = gen_embed_pruner.calculate_block_rankings(question, pruned_html)
![image](https://github.com/user-attachments/assets/4886d560-c126-4fc5-a32c-0c40cda4dc21)

**Comment by oreo34567** [comment]
and using the recommended settings
![image](https://github.com/user-attachments/assets/ebf24655-2ba3-4bbd-9dee-011759f92c54)

**Comment by plageon** [comment]
Thanks! This is a bug. Change the last line of your code like this:
`block_rankings=gen_embed_pruner.calculate_block_rankings(question, pruned_html, block_tree)`
We have fixed this in the latest [commit](https://github.com/plageon/HtmlRAG/commit/fdd1f44e6d940e2f34aee38b0a7b48ca6bc7843e).
