### ISSUE TITLE
剪枝的时候有报错怎么解决呢

### ISSUE THREAD

**Issue by LinXin04** [plageon/HtmlRAG#2]
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Cell In[19], line 6
      3 chat_tokenizer = AutoTokenizer.from_pretrained("/Qwen2.5-7B-Instruct")
      5 max_context_window = 60
----> 6 pruned_html = embed_html_pruner.prune_HTML(simplified_html, block_tree, block_rankings, chat_tokenizer, max_context_window)
      7 print("pruned_html:",pruned_html)

File /opt/conda/lib/python3.10/site-packages/htmlrag/pruner.py:25, in Pruner.prune_HTML(self, html, block_tree, block_rankings, chat_tokenizer, max_context_window)
     23 paths = [{"path": paths[i], "is_leaf": is_leaf[i]} for i in range(len(paths))]
     24 for idj in range(len(paths)):
---> 25     path_idx = int(block_rankings[idj])
     26     paths[path_idx]["ranking"] = idj
     28 soup = bs4.BeautifulSoup(html, 'html.parser')

IndexError: list index out of range

**Comment by plageon** [comment]
Thank you for following my work!
I check your error message. I think the length of the param `block_rankings` does not match the length of the param `block_rankings`. Maybe you could run the following code to debug:
```python
assert len(block_rankings)==len(block_tree), f"The number of block rankings {len(block_rankings)} should be equal to the number of blocks {len(block_tree)}"
```
Also, it seem the htmlrag version is old. Try install v0.0.3 and rerun.

**Comment by LinXin04** [comment]
thanks. 
**Question1:**

I think the error only happend when i use bm25 to rank the blocks. but I don't know why. The url I test is "https://www.canac.ca/"

######## solution1 ######## 
from htmlrag import EmbedHTMLPruner
embed_model="/bge-m3/bge-m3/"
query_instruction_for_retrieval = "Instruct: Given a web search query, retrieve relevant passages that answer the query\nQuery: "
embed_html_pruner = EmbedHTMLPruner(embed_model=embed_model, local_inference=True, query_instruction_for_retrieval = query_instruction_for_retrieval)
block_rankings=embed_html_pruner.calculate_block_rankings(question, simplified_html, block_tree)
print(block_rankings)
#[6, 12, 0, 1, 10, 4, 9, 5, 17, 16, 15, 14, 13, 2, 3, 7, 11, 8]

######## solution2 ######## 
from htmlrag import BM25HTMLPruner
bm25_html_pruner = BM25HTMLPruner()
block_rankings=bm25_html_pruner.calculate_block_rankings(question, simplified_html, block_tree)
print("block_rankings:",block_rankings)

#block_rankings: [17, 16, 15, 14]

**Question2:**
when i run prune, the pruned_html is None

from transformers import AutoTokenizer
chat_tokenizer = AutoTokenizer.from_pretrained("/Qwen2.5-7B-Instruct")
max_context_window=60
pruned_html = embed_html_pruner.prune_HTML(simplified_html, block_tree, block_rankings, chat_tokenizer, max_context_window)
print("pruned_html:",pruned_html)
#pruned_html:

**Comment by plageon** [comment]
We fix some bugs. I hope [v0.0.4](https://github.com/plageon/HtmlRAG/tree/v0.04) will help you.

**Comment by LinXin04** [comment]
Thanks so much! But when i run "pip install htmlrag==0.0.4", it warns that ERROR: Could not find a version that satisfies the requirement htmlrag==0.0.4 (from versions: 0.0.1, 0.0.2, 0.0.3)

**Comment by LinXin04** [comment]
Thanks,it worked. 
When I run GenHTMLPruner, some errors happened.The codes are as follows.

from htmlrag import GenHTMLPruner
ckpt_path = "./HTML-Pruner-Phi-3.8B"
gen_embed_pruner = GenHTMLPruner(gen_model=ckpt_path, max_node_words=10)
block_rankings = gen_embed_pruner.calculate_block_rankings(question, pruned_html)
print(block_rankings)
max_context_window = 32
pruned_html = gen_embed_pruner.prune_HTML(pruned_html, block_tree, block_rankings, chat_tokenizer, max_context_window)
print(pruned_html)

ModuleNotFoundError: No module named 'transformers_modules.HTML-Pruner-Phi-3'

**Comment by plageon** [comment]
Could you paste the detailed error stack trace?

**Comment by LinXin04** [comment]
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[92], line 4
      1 from htmlrag import GenHTMLPruner
      3 ckpt_path = "./HTML-Pruner-Phi-3.8B"
----> 4 gen_embed_pruner = GenHTMLPruner(gen_model=ckpt_path, max_node_words=10)
      5 block_rankings = gen_embed_pruner.calculate_block_rankings(question, pruned_html)
      6 print(block_rankings)

File /ossfs/node_49279467/workspace/HtmlRAG-main/toolkit/htmlrag/pruner.py:142, in GenHTMLPruner.__init__(self, gen_model, max_node_words, device)
    141 def __init__(self,  gen_model, max_node_words, device="cpu"):
--> 142     self.gen_model = AutoModelForSeq2SeqLM.from_pretrained(gen_model, trust_remote_code=True, torch_dtype=torch.bfloat16).eval()
    143     self.gen_model.to(device)
    144     self.gen_model.max_node_words = max_node_words

File /opt/conda/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py:553, in _BaseAutoModelClass.from_pretrained(cls, pretrained_model_name_or_path, *model_args, **kwargs)
    551 if has_remote_code and trust_remote_code:
    552     class_ref = config.auto_map[cls.__name__]
--> 553     model_class = get_class_from_dynamic_module(
    554         class_ref, pretrained_model_name_or_path, code_revision=code_revision, **hub_kwargs, **kwargs
    555     )
    556     _ = hub_kwargs.pop("code_revision", None)
    557     cls.register(config.__class__, model_class, exist_ok=True)

File /opt/conda/lib/python3.10/site-packages/transformers/dynamic_module_utils.py:552, in get_class_from_dynamic_module(class_reference, pretrained_model_name_or_path, cache_dir, force_download, resume_download, proxies, token, revision, local_files_only, repo_type, code_revision, **kwargs)
    539 # And lastly we get the class inside our newly created module
    540 final_module = get_cached_module_file(
    541     repo_id,
    542     module_file + ".py",
   (...)
    550     repo_type=repo_type,
    551 )
--> 552 return get_class_in_module(class_name, final_module, force_reload=force_download)

File /opt/conda/lib/python3.10/site-packages/transformers/dynamic_module_utils.py:249, in get_class_in_module(class_name, module_path, force_reload)
    247 # reload in both cases, unless the module is already imported and the hash hits
    248 if getattr(module, "__transformers_module_hash__", "") != module_hash:
--> 249     module_spec.loader.exec_module(module)
    250     module.__transformers_module_hash__ = module_hash
    251 return getattr(module, class_name)

File <frozen importlib._bootstrap_external>:883, in exec_module(self, module)

File <frozen importlib._bootstrap>:241, in _call_with_frames_removed(f, *args, **kwds)

File ~/.cache/huggingface/modules/transformers_modules/HTML-Pruner-Phi-3.8B/modeling_phi3.py:53
     43 from transformers.utils import (
     44     add_code_sample_docstrings,
     45     add_start_docstrings,
   (...)
     50     replace_return_docstrings,
     51 )
     52 from .configuration_phi3 import Phi3Config
---> 53 from .tree_gen_utils import split_tree, TokenIdNode, TokenDotExporter, nodenamefunc
     56 logger = logging.get_logger(__name__)
     58 # Transformers scans dependencies in the modeling file, causing issues on conditional loading. The regex only ignores try/catch blocks, but not if statements
     59 # if is_flash_attn_2_available():

ModuleNotFoundError: No module named 'transformers_modules.HTML-Pruner-Phi-3'

**Comment by plageon** [comment]
We fix some bugs for HTML-Pruner-Phi-3.8B. You could either re-download model or replace modeling_phi3 with the [new one](https://github.com/plageon/HtmlRAG/blob/main/llm_modeling/Phi35/modeling_phi3.py).

Also, specify the device if you are using gpu.
```python
from htmlrag import GenHTMLPruner
import torch

ckpt_path = "zstanjj/HTML-Pruner-Llama-1B"
if torch.cuda.is_available():
    device="cuda"
else:
    device="cpu"
gen_embed_pruner = GenHTMLPruner(gen_model=ckpt_path, max_node_words=5, device=device)
block_rankings = gen_embed_pruner.calculate_block_rankings(question, pruned_html)
print(block_rankings)

# [1, 0]

max_context_window = 32
pruned_html = gen_embed_pruner.prune_HTML(pruned_html, block_tree, block_rankings, chat_tokenizer, max_context_window)
print(pruned_html)

# <p>The Bellagio is a luxury hotel and casino located on the Las Vegas Strip in Paradise, Nevada. It was built in 1998.</p>
```

**Comment by LinXin04** [comment]
When i run the code below,an new error happend.
"block_rankings = gen_embed_pruner.calculate_block_rankings(question, pruned_html)
print(block_rankings)"
-------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[23], line 1
----> 1 block_rankings = gen_embed_pruner.calculate_block_rankings(question, pruned_html)
      2 print(block_rankings)

File /ossfs/node_49279467/workspace/HtmlRAG-main/toolkit/htmlrag/pruner.py:150, in GenHTMLPruner.calculate_block_rankings(self, question, html, block_tree)
    148 def calculate_block_rankings(self, question: str, html: str, block_tree: List[Tuple]=None):
    149     log_threshold = self.log_threshold
--> 150     html_res = self.gen_model.generate_html_tree(self.node_tokenizer, [question], [html])
    151     node_tree=html_res[0]["node_tree"]
    152     paths=html_res[0]["paths"]

File /opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py:116, in context_decorator.<locals>.decorate_context(*args, **kwargs)
    113 @functools.wraps(func)
    114 def decorate_context(*args, **kwargs):
    115     with ctx_factory():
--> 116         return func(*args, **kwargs)

File ~/.cache/huggingface/modules/transformers_modules/HTML-Pruner-Phi-3.8B/modeling_phi3.py:1967, in PHI3ForHTMLTreeGeneration.generate_html_tree(self, tokenizer, query, htmls, **kwargs)
   1965 child_input_ids = torch.cat([inputs["input_ids"][idx:idx + 1], child_input_ids], dim=1).to(self.device)
   1966 model_inputs = self.prepare_inputs_for_generation(child_input_ids, **kwargs)
-> 1967 outputs = self(
   1968     **model_inputs,
   1969     return_dict=True,
   1970 )
   1971 #  get the probability of force_token_id
   1972 force_token_id = torch.tensor(force_token_id, device=self.device)

File /opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py:1736, in Module._wrapped_call_impl(self, *args, **kwargs)
   1734     return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1735 else:
-> 1736     return self._call_impl(*args, **kwargs)

File /opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py:1747, in Module._call_impl(self, *args, **kwargs)
   1742 # If we don't have any hooks, we want to skip the rest of the logic in
   1743 # this function, and just call forward.
   1744 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1745         or _global_backward_pre_hooks or _global_backward_hooks
   1746         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1747     return forward_call(*args, **kwargs)
   1749 result = None
   1750 called_always_called_hooks = set()

File ~/.cache/huggingface/modules/transformers_modules/HTML-Pruner-Phi-3.8B/modeling_phi3.py:1770, in PHI3ForHTMLTreeGeneration.forward(self, input_ids, attention_mask, position_ids, past_key_values, inputs_embeds, labels, use_cache, output_attentions, output_hidden_states, return_dict)
   1767 return_dict = return_dict if return_dict is not None else self.config.use_return_dict
   1769 # decoder outputs consists of (dec_features, layer_state, dec_hidden, dec_attn)
-> 1770 outputs = self.model(
   1771     input_ids=input_ids,
   1772     attention_mask=attention_mask,
   1773     position_ids=position_ids,
   1774     past_key_values=past_key_values,
   1775     inputs_embeds=inputs_embeds,
   1776     use_cache=use_cache,
   1777     output_attentions=output_attentions,
   1778     output_hidden_states=output_hidden_states,
   1779     return_dict=return_dict,
   1780 )
   1782 hidden_states = outputs[0]
   1783 logits = self.lm_head(hidden_states)

File /opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py:1736, in Module._wrapped_call_impl(self, *args, **kwargs)
   1734     return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1735 else:
-> 1736     return self._call_impl(*args, **kwargs)

File /opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py:1747, in Module._call_impl(self, *args, **kwargs)
   1742 # If we don't have any hooks, we want to skip the rest of the logic in
   1743 # this function, and just call forward.
   1744 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1745         or _global_backward_pre_hooks or _global_backward_hooks
   1746         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1747     return forward_call(*args, **kwargs)
   1749 result = None
   1750 called_always_called_hooks = set()

File ~/.cache/huggingface/modules/transformers_modules/HTML-Pruner-Phi-3.8B/modeling_phi3.py:1233, in Phi3Model.forward(self, input_ids, attention_mask, position_ids, past_key_values, inputs_embeds, use_cache, output_attentions, output_hidden_states, return_dict)
   1223     layer_outputs = self._gradient_checkpointing_func(
   1224         decoder_layer.__call__,
   1225         hidden_states,
   (...)
   1230         use_cache,
   1231     )
   1232 else:
-> 1233     layer_outputs = decoder_layer(
   1234         hidden_states,
   1235         attention_mask=attention_mask,
   1236         position_ids=position_ids,
   1237         past_key_value=past_key_values,
   1238         output_attentions=output_attentions,
   1239         use_cache=use_cache,
   1240     )
   1242 hidden_states = layer_outputs[0]
   1244 if use_cache:

File /opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py:1736, in Module._wrapped_call_impl(self, *args, **kwargs)
   1734     return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1735 else:
-> 1736     return self._call_impl(*args, **kwargs)

File /opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py:1747, in Module._call_impl(self, *args, **kwargs)
   1742 # If we don't have any hooks, we want to skip the rest of the logic in
   1743 # this function, and just call forward.
   1744 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1745         or _global_backward_pre_hooks or _global_backward_hooks
   1746         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1747     return forward_call(*args, **kwargs)
   1749 result = None
   1750 called_always_called_hooks = set()

File ~/.cache/huggingface/modules/transformers_modules/HTML-Pruner-Phi-3.8B/modeling_phi3.py:952, in Phi3DecoderLayer.forward(self, hidden_states, attention_mask, position_ids, past_key_value, output_attentions, use_cache, **kwargs)
    949 hidden_states = self.input_layernorm(hidden_states)
    951 # Self Attention
--> 952 attn_outputs, self_attn_weights, present_key_value = self.self_attn(
    953     hidden_states=hidden_states,
    954     attention_mask=attention_mask,
    955     position_ids=position_ids,
    956     past_key_value=past_key_value,
    957     output_attentions=output_attentions,
    958     use_cache=use_cache,
    959 )
    961 hidden_states = residual + self.resid_attn_dropout(attn_outputs)
    963 residual = hidden_states

File /opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py:1736, in Module._wrapped_call_impl(self, *args, **kwargs)
   1734     return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1735 else:
-> 1736     return self._call_impl(*args, **kwargs)

File /opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py:1747, in Module._call_impl(self, *args, **kwargs)
   1742 # If we don't have any hooks, we want to skip the rest of the logic in
   1743 # this function, and just call forward.
   1744 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1745         or _global_backward_pre_hooks or _global_backward_hooks
   1746         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1747     return forward_call(*args, **kwargs)
   1749 result = None
   1750 called_always_called_hooks = set()

File ~/.cache/huggingface/modules/transformers_modules/HTML-Pruner-Phi-3.8B/modeling_phi3.py:523, in Phi3FlashAttention2.forward(self, hidden_states, attention_mask, position_ids, past_key_value, output_attentions, use_cache, **kwargs)
    519 if not _flash_supports_window_size:
    520     logger.warning_once(
    521         "The current flash attention version does not support sliding window attention. Please use `attn_implementation='eager'` or upgrade flash-attn library."
    522     )
--> 523     raise ValueError("The current flash attention version does not support sliding window attention.")
    525 output_attentions = False
    527 if "padding_mask" in kwargs:

ValueError: The current flash attention version does not support sliding window attention.

**Comment by plageon** [comment]
Perhaps your flash_attn version does not match.
Alternatively you can use other attention implementations.
