### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by LinXin04** [plageon/HtmlRAG#3]
when I run the following code, some error happened.

```python
from htmlrag import GenHTMLPruner
import torch

ckpt_path = "./HTML-Pruner-Llama-1B"
if torch.cuda.is_available():
    device="cuda"
else:
    device="cpu"
gen_embed_pruner = GenHTMLPruner(gen_model=ckpt_path, max_node_words=5, device=device)
block_rankings = gen_embed_pruner.calculate_block_rankings(question, pruned_html)
print(block_rankings)

# [1, 0]

max_context_window = 32
pruned_html = gen_embed_pruner.prune_HTML(pruned_html, block_tree, block_rankings, chat_tokenizer, max_context_window)
print(pruned_html)
```

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Cell In[6], line 16
     13 # [1, 0]
     15 max_context_window = 32
---> 16 pruned_html = gen_embed_pruner.prune_HTML(pruned_html, block_tree, block_rankings, chat_tokenizer, max_context_window)
     17 print(pruned_html)
     19 # <p>The Bellagio is a luxury hotel and casino located on the Las Vegas Strip in Paradise, Nevada. It was built in 1998.</p>

File /opt/conda/lib/python3.10/site-packages/htmlrag/pruner.py:25, in Pruner.prune_HTML(self, html, block_tree, block_rankings, chat_tokenizer, max_context_window)
     23 paths = [{"path": paths[i], "is_leaf": is_leaf[i]} for i in range(len(paths))]
     24 for idj in range(len(paths)):
---> 25     path_idx = int(block_rankings[idj])
     26     paths[path_idx]["ranking"] = idj
     28 soup = bs4.BeautifulSoup(html, 'html.parser')

IndexError: list index out of range

**Comment by plageon** [comment]
I think this issue is pretty much like your last one. The length of the param `block_rankings` does not match the length of the param `block_rankings`. Maybe you could run the following code to debug:
```python
assert len(block_rankings)==len(block_tree), f"The number of block rankings {len(block_rankings)} should be equal to the number of blocks {len(block_tree)}"
```

**Comment by LinXin04** [comment]
I use your case in https://github.com/plageon/HtmlRAG/tree/main/toolkit
#####
from htmlrag import GenHTMLPruner
import torch

ckpt_path = "./HTML-Pruner-Llama-1B"
if torch.cuda.is_available():
    device="cuda"
else:
    device="cpu"
gen_embed_pruner = GenHTMLPruner(gen_model=ckpt_path, max_node_words=5, device=device)
block_rankings = gen_embed_pruner.calculate_block_rankings(question, pruned_html)
print(block_rankings)
#########
#block_rankings=[0, 1]
assert len(block_rankings)==len(block_tree), f"The number of block rankings {len(block_rankings)} should be equal to the number of blocks {len(block_tree)}"
#AssertionError: The number of block rankings 2 should be equal to the number of blocks 3

**Comment by LinXin04** [comment]
![image](https://github.com/user-attachments/assets/40a949d7-5ee2-40a3-92c8-64d22a507e33)

**Comment by plageon** [comment]
Sorry for the confusion. We expect the block tree should be parsed for a second time after the first stage pruning. You could try the piece of code below.
```python
from htmlrag import GenHTMLPruner
import torch

ckpt_path = "zstanjj/HTML-Pruner-Llama-1B"
if torch.cuda.is_available():
    device="cuda"
else:
    device="cpu"
gen_embed_pruner = GenHTMLPruner(gen_model=ckpt_path, max_node_words=5, device=device)
block_rankings = gen_embed_pruner.calculate_block_rankings(question, pruned_html)
print(block_rankings)

# [1, 0]

block_tree, pruned_html=build_block_tree(pruned_html, max_node_words=10)
for block in block_tree:
    print("Block Content: ", block[0])
    print("Block Path: ", block[1])
    print("Is Leaf: ", block[2])
    print("")
    
# Block Content:  <title>When was the bellagio in las vegas built?</title>
# Block Path:  ['html', 'title']
# Is Leaf:  True
# 
# Block Content:  <p>The Bellagio is a luxury hotel and casino located on the Las Vegas Strip in Paradise, Nevada. It was built in 1998.</p>
# Block Path:  ['html', 'p']
# Is Leaf:  True

max_context_window = 32
pruned_html = gen_embed_pruner.prune_HTML(pruned_html, block_tree, block_rankings, chat_tokenizer, max_context_window)
print(pruned_html)

# <p>The Bellagio is a luxury hotel and casino located on the Las Vegas Strip in Paradise, Nevada. It was built in 1998.</p>
```

**Comment by LinXin04** [comment]
Thanks.but when I run as the above codes, the result of pruned_html is "<title>When was the bellagio in las vegas built?</title>". I think the result is not meeting expectations.

**Comment by LinXin04** [comment]
The whole codes are as follows.
from htmlrag import clean_html

question = "When was the bellagio in las vegas built?"
html = """
<html>
<head>
<title>When was the bellagio in las vegas built?</title>
</head>
<body>
<p class="class0">The Bellagio is a luxury hotel and casino located on the Las Vegas Strip in Paradise, Nevada. It was built in 1998.</p>
</body>
<div>
<div>
<p>Some other text</p>
<p>Some other text</p>
</div>
</div>
<p class="class1"></p>

<script type="text/javascript">
document.write("Hello World!");
</script>
</html>
"""

simplified_html = clean_html(html)
print(simplified_html)
from htmlrag import build_block_tree

block_tree, simplified_html = build_block_tree(simplified_html, max_node_words=10)
for block in block_tree:
    print("Block Content: ", block[0])
    print("Block Path: ", block[1])
    print("Is Leaf: ", block[2])
    print("")
    
from htmlrag import EmbedHTMLPruner

embed_model="/bge-m3/bge-m3"
query_instruction_for_retrieval = "Instruct: Given a web search query, retrieve relevant passages that answer the query\nQuery: "
embed_html_pruner = EmbedHTMLPruner(embed_model=embed_model, local_inference=True, query_instruction_for_retrieval = query_instruction_for_retrieval)
# alternatively you can init a remote TEI model, refer to https://github.com/huggingface/text-embeddings-inference.
# tei_endpoint="http://YOUR_TEI_ENDPOINT"
# embed_html_pruner = EmbedHTMLPruner(embed_model=embed_model, local_inference=False, query_instruction_for_retrieval = query_instruction_for_retrieval, endpoint=tei_endpoint)
block_rankings=embed_html_pruner.calculate_block_rankings(question, simplified_html, block_tree)
print(block_rankings)


from transformers import AutoTokenizer

chat_tokenizer = AutoTokenizer.from_pretrained("/Qwen2.5-7B-Instruct")

max_context_window = 60
pruned_html = embed_html_pruner.prune_HTML(simplified_html, block_tree, block_rankings, chat_tokenizer, max_context_window)
print(pruned_html)

from htmlrag import GenHTMLPruner
import torch

ckpt_path = "./HTML-Pruner-Llama-1B"
if torch.cuda.is_available():
    device="cuda"
else:
    device="cpu"
gen_embed_pruner = GenHTMLPruner(gen_model=ckpt_path, max_node_words=5, device=device)
block_rankings = gen_embed_pruner.calculate_block_rankings(question, pruned_html)
print(block_rankings)

# [1, 0]

block_tree, pruned_html=build_block_tree(pruned_html, max_node_words=10)
for block in block_tree:
    print("Block Content: ", block[0])
    print("Block Path: ", block[1])
    print("Is Leaf: ", block[2])
    print("")
    
# Block Content:  <title>When was the bellagio in las vegas built?</title>
# Block Path:  ['html', 'title']
# Is Leaf:  True
# 
# Block Content:  <p>The Bellagio is a luxury hotel and casino located on the Las Vegas Strip in Paradise, Nevada. It was built in 1998.</p>
# Block Path:  ['html', 'p']
# Is Leaf:  True

max_context_window = 32
pruned_html = gen_embed_pruner.prune_HTML(pruned_html, block_tree, block_rankings, chat_tokenizer, max_context_window)
print(pruned_html)

# <p>The Bellagio is a luxury hotel and casino located on the Las Vegas Strip in Paradise, Nevada. It was built in 1998.</p>

**Comment by plageon** [comment]
Maybe you could try `zstanjj/HTML-Pruner-Phi-3.8B` as the HTML pruner model.
