### ISSUE TITLE
No code for /evaluate_utils/bleu/

### ISSUE THREAD

**Issue by andygoosh** [plageon/HtmlRAG#6]
https://github.com/plageon/HtmlRAG/blob/42552d81c73f62aa2f88c1aa3b9c897ca71f82d9/evaluate_utils/__init__.py#L43

There no code in evaluate_utils for bleu. Is it a mistake? Shall it be bleu=evaluate.load("bleu") instead?

**Comment by plageon** [comment]
https://github.com/plageon/HtmlRAG/commit/5e7ac94c8427d8254379090ac0b29beab97091bc

**Comment by andygoosh** [comment]
Thank you for the prompt action! Fantastic work
