### ISSUE TITLE
Missing jsonl files

### ISSUE THREAD

**Issue by andygoosh** [plageon/HtmlRAG#7]
https://github.com/plageon/HtmlRAG/blob/5e7ac94c8427d8254379090ac0b29beab97091bc/jupyter/eval_scrips.ipynb#L46

The code references a bunch of jsonl files which are not in the repo. Do those get generated somehow? 
I have one more preference to note: reading from the output file feels unusual.

**Comment by plageon** [comment]
No, the generated answers are not provided yet.
