### ISSUE TITLE
Some problems running the tree_rerank.sh file

### ISSUE THREAD

**Issue by Morning-Z** [plageon/HtmlRAG#8]
Hello, I got the following error when reproducing the code. Can you give me an answer? Thank you very much!  
<img width="1405" alt="image" src="https://github.com/user-attachments/assets/85869960-7077-4492-940a-9600d3496599">

**Comment by plageon** [comment]
I'm afraid your error discription is unclear. It seems there is some problem with your network connection to hugginface. Also, your json string is mal-formatted.

**Comment by Morning-Z** [comment]
Is the URL of my model wrong? I am using the API of the bgelargeen model, and the others are based on your source code.

**Comment by plageon** [comment]
Is the embedding server based on tei? It seems the request and return formats of your server are not compatible with the source code.

**Comment by Morning-Z** [comment]
It can output the embedding vector, but reports
ValueError: documents and embeddings expected to be equal length but len(documents)=256 and len(embeddings)=0

**Comment by Morning-Z** [comment]
May I know what the output of the bgelargeen model looks like?

**Comment by plageon** [comment]
Refer to the official document or [repo](https://github.com/huggingface/text-embeddings-inference).
My experimental evironment: 
-  Docker version: ghcr.io/huggingface/text-embeddings-inference:1.5
- Service starting command (replace ${MODEL_ID} with your bge ckpt path): 
  ```bash
  text-embeddings-router --model-id ${MODEL_ID} --port 80 --dtype float16 --max-client-batch-size 256 --max-batch-requests 256 --auto-truncate
  ```

**Comment by Morning-Z** [comment]
I have solved this problem, thank you very much for your help
